# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'LinekeLive' do

	pod 'AFNetworking', '~> 3.1.0'
	pod 'Masonry', '~> 1.0.2'
	pod 'YYKit', '~> 1.0.9'
	pod 'SDWebImage', '~> 4.0.0'
	pod 'MJExtension', '~> 3.0.13'
	pod 'MJRefresh', '~> 3.1.12'
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'SVProgressHUD', '~> 2.1.2'
	pod 'LFLiveKit', '~> 2.6'

end
